--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/udachin26/BedrockEssentials
build-by-default: true
branches:
- main
projects:
  BedrockEssentials:
    path: ""
    libs:
      - src: CortexPE/Commando/Commando
        version: ^3.0.0
        branch: PM4
      - src: poggit/libasynql/libasynql
        version: ^4.0.1
    lint: false
...
