name: uEssentials
main: udachin26\uessentials\uEssentials
src-namespace-prefix: udachin26\uessentials
version: 0.0.1
api: 4.3.0
load: POSTWORLD
author: udachin26
description: uEssentials is plugin for PocketMine-MP with necessary functions
website: https://github.com/udachin26/uEssentials
virions: ["Commando", "libasynql"]