name: BedrockEssentials
main: udachin26\bedrockessentials\BedrockEssentials
version: 0.0.1
api: 4.2.5

load: POSTWORLD
author: udachin26
description: BedrockEssentials is plugin for PocketMine-MP with necessary functions
website: https://github.com/udachin26/BedrockEssentials